import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8

[window.padding]
#x = 25
#y = 20

[font]
size = 24.0

[font.bold]
family = "MesloLGL Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Medium Italic"

[font.normal]
family = "MesloLGL Nerd Font"
